// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUjzlwXOFwpGppDo9Yhs3POAYTAG7hVtE',
    appId: '1:858875368286:web:558f0f8ab77e90e181b5cf',
    messagingSenderId: '858875368286',
    projectId: 'pill-tracker-f64c9',
    authDomain: 'pill-tracker-f64c9.firebaseapp.com',
    storageBucket: 'pill-tracker-f64c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUjzlwXOFwpGppDo9Yhs3POAYTAG7hVtE',
    appId: '1:858875368286:android:your-android-app-id',
    messagingSenderId: '858875368286',
    projectId: 'pill-tracker-f64c9',
    storageBucket: 'pill-tracker-f64c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUjzlwXOFwpGppDo9Yhs3POAYTAG7hVtE',
    appId: '1:858875368286:ios:your-ios-app-id',
    messagingSenderId: '858875368286',
    projectId: 'pill-tracker-f64c9',
    storageBucket: 'pill-tracker-f64c9.firebasestorage.app',
    iosClientId: 'your-ios-client-id',
    iosBundleId: 'com.example.smartPillTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUjzlwXOFwpGppDo9Yhs3POAYTAG7hVtE',
    appId: '1:858875368286:ios:your-ios-app-id',
    messagingSenderId: '858875368286',
    projectId: 'pill-tracker-f64c9',
    storageBucket: 'pill-tracker-f64c9.firebasestorage.app',
    iosClientId: 'your-ios-client-id',
    iosBundleId: 'com.example.smartPillTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUjzlwXOFwpGppDo9Yhs3POAYTAG7hVtE',
    appId: '1:858875368286:web:558f0f8ab77e90e181b5cf',
    messagingSenderId: '858875368286',
    projectId: 'pill-tracker-f64c9',
    authDomain: 'pill-tracker-f64c9.firebaseapp.com',
    storageBucket: 'pill-tracker-f64c9.firebasestorage.app',
  );
}